### ISSUE TITLE
Pushing .so files for 52 and 61 versions

### ISSUE THREAD

**Issue by NickShahML** [MycChiu/fast-LayerNorm-TF#1]
Hey @MycChiu , great work you've done here. I wanted to test your speed up. However, I'm running into a many problems when I make. Can you push the .so compiled file versions for 52 and 61 gpu configs? Thanks alot!

**Comment by MycChiu** [comment]
Thanks man, I am glad some other people could use this code. Sorry for the late response, I have added the compiled files, please let me know if you run into other problems.

**Comment by NickShahML** [comment]
Big thanks -- if you want to collaborate on making more monolithic ops let me know. I"m in the process of making monolithic ops for highway RNN and many more mechanisms.

**Comment by MycChiu** [comment]
Sure thing, just let me know if there's anything I can help with. I just realized you are the creator of [tensorflow_with_latest_papers](https://github.com/NickShahML/tensorflow_with_latest_papers), I really learned a lot from your code, thank you so much!

**Comment by NickShahML** [comment]
Haha no problem, what goes around comes around. Do you mind adding me on skype? my name is leavesbreathe
