### ISSUE TITLE
Errors using layer_norm_fused_op.so file

### ISSUE THREAD

**Issue by AzizCode92** [MycChiu/fast-LayerNorm-TF#5]
I run make with success and then copied the compiled .so file to /usr/local/cuda/lib64/.
When I run the "layer_norm_fused_test.py" I got an error saying: 

`lib_handle = py_tf.TF_LoadLibrary(library_filename) 
tensorflow.python.framework.errors_impl.NotFoundError: /usr/local/cuda-9.0/lib64/layer_norm_fused_op.so: undefined symbol: _ZTIN10tensorflow8OpKernelE`

further details : 
`Cuda compilation tools, release 9.0, V9.0.176 \
  Tensorflow version :  1.10.0
`

**Comment by vsuthichai** [comment]
@AzizCode92 Did you end up resolving this problem?  I'm experiencing the same issue.

**Comment by AzizCode92** [comment]
please consider this pull-request : https://github.com/MycChiu/fast-LayerNorm-TF/pull/3/files
My code is in aws instance that it is shutdown now.
If the pull request doesnt solve your problem I will share my makefile with you asap.

bests

**Comment by vsuthichai** [comment]
@AzizCode92 Didn't work for me unfortunately, would you be able to share your makefile?  Thanks so much!

**Comment by AzizCode92** [comment]
TF_INC :=$(shell python -c 'import tensorflow as tf; print(tf.sysconfig.get_include())')
TF_LIB :=$(shell python -c 'import tensorflow as tf; print(tf.sysconfig.get_lib())')
INC=-I${TF_INC}
LIB=-L${TF_LIB}
layer_norm_fused_op: register_ops.cc layer_norm_fused_op.h layer_norm_fused_op.cc layer_norm_fused_grad_op.cc layer_norm_fused_op_gpu.cu.cc
        nvcc -std=c++11 -c -o layer_norm_fused_op_gpu.cu.o layer_norm_fused_op_gpu.cu.cc \
        $(INC) -D GOOGLE_CUDA=1 -x cu -Xcompiler -fPIC --expt-relaxed-constexpr -gencode=arch=compute_35,code=sm_35 \
        -gencode=arch=compute_50,code=sm_50 -gencode=arch=compute_52,code=sm_52 \
        -gencode=arch=compute_60,code=sm_60 -gencode=arch=compute_61,code=sm_61 -gencode=arch=compute_61,code=compute_61
        g++ -std=c++11 -shared -o layer_norm_fused_op.so register_ops.cc layer_norm_fused_op.h \
        layer_norm_fused_grad_op.cc layer_norm_fused_op.cc layer_norm_fused_op_gpu.cu.o \
        $(INC) $(LIB) -ltensorflow_framework -L /usr/local/cuda/lib64/ -fPIC -D_GLIBCXX_USE_CXX11_ABI=0 -lcudart -O2 -DNDEBUG

**Comment by vsuthichai** [comment]
@AzizCode92 Works now.  It turned out `-D_GLIBCXX_USE_CXX11_ABI=0` wasn't necessary.  It was missing the library location and library to link with.  Thank you!
